version: "2"
services:
  producer:
    build: ./producer/
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
  redis:
    image: redis
